title: Freesouls.cc
description: ""
exclude: [README.md, LICENSE.txt, Gemfile, Gemfile.lock, Rakefile, config, lib]
gems: ["jekyll-paginate", "jekyll-feed", "jekyll-redirect-from"]

url: https://freesouls.cc

paginate_path: "/blog/page:num/"
paginate: 10

email: books@freesouls.cc
github_username: freesouls-cc
twitter_username: FreesoulsCC

source_url: "https://github.com/freesouls-cc/freesouls.cc/blob/master/"

license: "Creative Commons Attribution License"
license_url: https://creativecommons.org/licenses/by/4.0/

ga: "UA-6367104-1"

orders:
  book: 79
  box: 379
  book_id: "WA62NHTW4T32Q"
  box_id: "UREL6V5T5S7R8"

feed:
  path: atom.xml

collections:
  essays:
    output: true
  book:
    output: true
  pic:
    output: true
  freesoulsbook:
    output: true
  modelrelease:
    output: true
  newrelease:
    output: true
  needrelease:
    output: true

defaults:
  - scope:
      path: ""
      type: essays
    values:
      layout: essay
      permalink: /essays/:title.html
  - scope:
      path: ""
      type: book
    values:
      layout: page
      permalink: /:title.html
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /:year/:month/:title.html
  - scope:
      path: ""
      type: pic
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: ""
      type: freesoulsbook
    values:
      layout: pic
      permalink: pic/:title/
  - scope:
      path: ""
      type: newrelease
    values:
      layout: modelrelease
      permalink: pic-newreleases/:title/
  - scope:
      path: ""
      type: modelrelease
    values:
      layout: modelrelease
      permalink: pic-released/:title/
  - scope:
      path: ""
      type: needrelease
    values:
      layout: needrelease
      permalink: pic-unreleased/:title/
